[tool.poetry]
name = "task-manager-core"
version = "0.1.0"
description = ""
authors = ["Kaziamov <kaziamov@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
